### ISSUE TITLE
Flow control code color

### ISSUE THREAD

**Issue by luki1412** [jasontheiler/kelp-forest-theme-vscode#1]
Love the theme, but wanted to ask ... how can I change the color of flow control code like an **If** statement, **for**,**foreach**,**switch** etc. to a different color because in powershell these blend in with variable types.
![colorissue](https://user-images.githubusercontent.com/20016096/82048054-2f4bd500-96b4-11ea-8e6b-ecfbe916bc03.png)

**Comment by jasontheiler** [comment]
First of all, thank you!

To your issue:

You should be able to inspect editor tokens and scopes by opening the **Command Palette** menu (`Ctrl+Shift+P` or `⌘+Shift+P`) and select **Developer: Inspect Editor Tokens and Scope**. You can then see information about the code syntax in a tooltip where your cursor is located.

![inspect](https://user-images.githubusercontent.com/50220557/82824328-6cc91300-9ea9-11ea-877a-62a16be9c4ef.png)

`textmate scopes` shows all the available scopes.
`foreground` shows the currently used scope and the assigned color.

You can then go ahead and for example add the following to your `settings.json` to override theme settings:

```json
"editor.tokenColorCustomizations": {
  "textMateRules": [
    {
      "name": "Keywords",
      "scope": ["keyword"],
      "settings": {
        "foreground": "#FF0000"
      }
    }
  ]
}
```

**Comment by luki1412** [comment]
Thank you. Very helpful.
Resolved my issue.
